### ISSUE TITLE
binaryReportFile leads to exclusion of tests

### ISSUE THREAD

**Issue by SimonedeGijt** [Kotlin/kotlinx-kover#152]
Hey guys, 

Today I noticed that when I add `binaryReportFile.set(file("$buildDir/custom/result.bin"))` to my build.gradle.kts that suddenly the tests inside my normal `test` source folder are not taken into account anymore. Interestingly enough the `itest` source folder is still taken into account. 

See my example project over here: 
[example-kover-main.zip](https://github.com/Kotlin/kotlinx-kover/files/8239825/example-kover-main.zip)

Steps to reproduce:
- Run `koverReport`
- Open HTML report and check package `org.example.greeting` -> GreetingService (all lines are green)
- Now uncomment line 61 of the build.gradle.kts + reload gradle project
- Run `koverReport`
- Open HTML report and check package `org.example.greeting` -> GreetingService (line 9, covered by the unittest inside of the `test` source folder is not covered anymore)

Have a nice day!

**Comment by shanshin** [comment]
Hi, sorry for the delayed answer.

You have several different test tasks: `test` and `integrationTest`.
In your build script, you configure not one specific task, but all tasks with the type `Test`
```
    withType<Test> {
        ...
        extensions.configure(KoverTaskExtension::class) {
          ...
          binaryReportFile.set(file("$buildDir/custom/result.bin"))
        }
    }
```
It turns out that for both test tasks you specified the same name of the binary file of the report. The last executed task overwrites this file and not all calls are counted in the report.

You can rewrite the script as follows so that the example works
```
    withType<Test> {
        useJUnitPlatform {
            excludeTags("smoke")
        }

        extensions.configure(KoverTaskExtension::class) {
            isDisabled = false
              binaryReportFile.set(file("$buildDir/custom/$name-result.bin"))
            includes = listOf("org.example.*")
        }
    }
```
