### ISSUE TITLE
Issues with exclusions

### ISSUE THREAD

**Issue by mattinger** [Kotlin/kotlinx-kover#153]
I'm using the default coverage engine settings for kover.  I also have an exclusion to remove the generaged dagger MembersInjector from instrumentation:

```
        "**/*MembersInjector*.*",
```

I can see that the exclusions are making their way into the KoverTaskExtension.  However, i still can't get rid of these classes from my report (i'd rather exclude from instrumentation than from the report).  It's also worth nothing that other generated classes BR and BuildConfig are also still showing up despite having patterns to remove them.

**Comment by Kobting** [comment]
I ran into this issue as well and it has to do with the difference in how to specify exclusion in kover vs jacoco.

In jacoco the exclusions are file path based and in kover they are not. 

For your example this would exclude the MembersInjector generated by dagger:

```
com.example.**.*MembersInjector*
```

Some other examples:
```
com.example.*.BuildConfig
com.example.*.BR
```

**Comment by shanshin** [comment]
Hi,
exclusion rules are represented as a set of fully-qualified names of the classes being instrumented.
It's possible to use `*` and `?` wildcards.

@mattinger you need to use the class name, not the file name. The class name does not contain an extension `.java`, `.kt` etc. and the path separator `/`.

Instead of  `"**/*MembersInjector*.*"`, you may write ` "*.*MembersInjector*"`. Also there is no special wildcard `**`, this is similar `*`.

In Gradle, JaCoCo exclusion rules are written in the same way, only using wildcards `*` and `?`.

**Comment by shanshin** [comment]
Feel free to reopen if there are additional questions.
