### ISSUE TITLE
koverMergedHtmlReport not ignoring provided classes

### ISSUE THREAD

**Issue by ymaniz09** [Kotlin/kotlinx-kover#197]
Hi,

When I run the `koverHtmlReport` for the app module or any other module, Kover ignores all Class names I'm providing.
When I run `koverMergedHtmlReport` it is not.

My configuration:

```
class KoverPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        target.setupTestCoverage()
    }
    
    private fun Project.setupTestCoverage() {
        extensions.getByType<BaseExtension>().run {
            testOptions {
                unitTests.all {
                    it.extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
                        isDisabled = it.name != "testDebugUnitTest"

                        excludes = ExcludedReportPatterns.asList()
                    }
                }
            }
        }

        tasks.withType(kotlinx.kover.tasks.KoverHtmlReportTask::class.java) {
            excludes = ExcludedReportPatterns.asList()
        }

        tasks.withType(kotlinx.kover.tasks.KoverMergedHtmlReportTask::class.java) {
            isEnabled = true

            excludes = ExcludedReportPatterns.asList()
        }
    }
}
```

Thanks in advance for helping me understand what I'm doing wrong.

**Comment by shanshin** [comment]
Hi,
may you clarify, is your plugin applied in the same project as Kover?

**Comment by ymaniz09** [comment]
This is my top-level `build.gradle.kts`:

```
plugins {
    ...
    id("org.jetbrains.kotlinx.kover")
}
```

And my plugin is applied in all projects/modules.

**Comment by shanshin** [comment]
Is your plugin applied in the top-level `build.gradle.kts`?

**Comment by ymaniz09** [comment]
🤔  it could be that...

From https://github.com/Kotlin/kotlinx-kover#configuring-jvm-test-task, I understood that I'd need to add

```
testOptions {
    unitTests.all {
         it.extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
         isDisabled = it.name != "testDebugUnitTest"

         excludes = ExcludedReportPatterns.asList()
         }
    }
}
```
to all my Android modules, so I'm applying the KoverPlugin I mentioned above to all `build.gradle.kts` but not for the top-level `build.gradle.kts`.

**Comment by shanshin** [comment]
According [docs](https://github.com/Kotlin/kotlinx-kover#configuring-merged-reports): `... you may configure the corresponding tasks in the project in which the plugin is applied (usually this is the root project):`.
In Kover 0.5.x merged tasks are created only in the project in which the Kover plugin is applied.

In your case if you don't apply your plugin in root project the code 
```
        tasks.withType(kotlinx.kover.tasks.KoverMergedHtmlReportTask::class.java) {
            isEnabled = true

            excludes = ExcludedReportPatterns.asList()
        }
```
does nothing since the task `kotlinx.kover.tasks.KoverMergedHtmlReportTask` do not exist in the projects in which your plugin is used.


To exclude classes from the merged report, you need to configure `KoverMergedHtmlReportTask` task only in the project in which you applied Kover plugin.

**Comment by ymaniz09** [comment]
Thank you so much! It's working perfectly =]
