### ISSUE TITLE
Set xml report path

### ISSUE THREAD

**Issue by Ivan3fonov** [Kotlin/kotlinx-kover#355]
Hi, I tried to set xml report file path but it doesn't work or maybe I've done something wrong.

**Platform**: Android,
**Gradle**:  Kotlin DSL(kts), 
**Version**: 0.7.0- Beta

```
 extensions.configure<kotlinx.kover.gradle.plugin.dsl.KoverReportExtension> {
        filters {
           ...
        }
        defaults {
            xml {
                setReportFile(layout.buildDirectory.file("kover/my_report.xml"))
            }
 ...
```
it always generates my xml report in `build/reports/kover/report<buildVariant>.xml`

It will be awesome if someone help me, thanks

**Comment by shanshin** [comment]
Hi,
the `defaults` block configures only reports that are generated using the `koverXmlReport`, `koverHtmlReport` etc commands (called default reports).
Reports for Android build variants cannot be configured in one place, because each variant must have its own report file/directory.

To change the file path of a specific Android build variant, you need to configure the report specifically for it
```
    androidReports("buildVariant") {
        xml {
            setReportFile(layout.buildDirectory.file("kover/my_report.xml"))
        }
    }
```


Alternatively, you can add the required build variant to the default reports
```
        defaults {
            mergeWith("buildVariant")
            xml {
                setReportFile(layout.buildDirectory.file("kover/my_report.xml"))
            }
        }
```
and generate a report using the commands `koverXmlReport`, `koverHtmlReport` etc 
However, keep in mind that in this case it is not recommended to add multiple build variants to the default reports, because this may cause report generation errors due to duplication of some classes in different variants.

**Comment by Ivan3fonov** [comment]
Thank you, resolved!
