### ISSUE TITLE
0.7.0-Beta: does not run tests on multiplatform

### ISSUE THREAD

**Issue by glureau** [Kotlin/kotlinx-kover#358]
**Describe the bug**
Tasks like koverVerify or koverHtmlReport doesn't run tests anymore, and the task ends up in "SKIPPED" (gradle state).

**Errors**
None.

**Expected behavior**
Tests to be run, html to be produced

**Reproducer**
No reproducer atm, but here's my gradle configuration:

```
        target.apply(plugin = "org.jetbrains.kotlinx.kover")
        target.extensions.configure(KoverReportExtension::class.java) {
            filters {
                includes {
                    classes("com.sumup.oms.*")
                }
            }
            defaults {
                filters {
                    includes {
                        classes("com.sumup.oms.*")
                    }
                }
                html {
                    filters {
                        includes {
                            classes("com.sumup.oms.*")
                        }
                    }
                }
                verify {
                    rule {
                        this.isEnabled = true
                    }
                }
            }
        }
```
I'm using this gradle plugin in KMM project, having iOS and Android enabled. Really I'm not doing anything fancy, just wanted to have a html report of the coverage.

**Environment**
 - Kover Gradle Plugin version: 0.7.0-Alpha
 - Gradle version: 7.6
 - Kotlin project type: Kotlin/Multiplatform
 - Coverage Engine version (if customized in build script): both engines have the same result

**Attempt of workaround**

I've tried to use `dependsOn` to link testDebugUnitTests on all tasks having "kover" and "verify"/"report" in the name, it triggers the tests but the kover tasks doesn't take the result as input.

**Comment by shanshin** [comment]
Hi,
if there are no JVM target in your multiplatform project, but only local unit tests for android target, then running `koverVerify` or `koverHtmlReport` tasks will not generate a report.

In this case, you need to either generate a report for the Android build variant you are interested in using the `koverVerify<BuildVariant>` commands (for example, `koverVerifyRelease`) or you need to add a report for a specific build variant to the default reports, so that you can generate reports using the commands `koverVerify`, `koverHtmlReport` etc.
```
koverReport {

    defaults {
        // add reports of 'release' Android build variant to default reports - generated by tasks `koverXmlReport`, `koverHtmlReport` etc
        mergeWith("release")
    }

}
```
