### ISSUE TITLE
Automatically open html report after it is generated

### ISSUE THREAD

**Issue by bakjoul** [Kotlin/kotlinx-kover#359]
**Describe what you would like to clarify about Kover**
Hello,
I'm new to kover. I'm used to Jacoco with which i use a script that automatically opens the report after it's generated.
I tried adapting it to use with kover but without success.

I'm trying with something like this :
```
android.applicationVariants.all { variant ->
    def variantName = variant.name.capitalize()

    task("koverHtmlReport${variantName}", type: koverHtmlReport, dependsOn: "test${variantName}UnitTest'") {
        group = "Reporting"
        description = "Generates HTML report for debug code coverage."

        def htmlOutDir = file("$buildDir/reports/kover/html${variantName}")

        doLast {
            openReport htmlOutDir
        }
    }
}
```

I don't even know if it would work but i can't even get the type right, i get this error :
> Caused by: com.android.build.gradle.internal.crash.ExternalApiUsageException: groovy.lang.MissingPropertyException: Could not get unknown property 'koverHtmlReport' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

Is there a simple way to automatically open the html reports ?

**Comment by shanshin** [comment]
Hi,
judging by the error `Could not get unknown property 'koverHtmlReport'` Gradle could not process the `type: koverHtmlReport,` code correctly.

Kover has already automatically created report generation tasks for each build variant. You do not need to create them again, it is enough to configure the existing ones, for example:

```
afterEvaluate {

    android.applicationVariants.all { variant ->
        def variantName = variant.name.capitalize()
        def htmlOutDir = file("$buildDir/reports/kover/html${variantName}")
        
        tasks.named("koverHtmlReport${variantName}").configure {
            doLast {
                openReport htmlOutDir
            }
        }
    }

}
```

Note that when using `named`, it is mandatory to execute this code in `afterEvaluate`, because Kover tasks are created at this stage

**Comment by bakjoul** [comment]
Hi,
This is exactly what i was looking for. Thank you very much !
