### ISSUE TITLE
Exclude calls to functions that are effectively constants (e.g. `.dp` in Compose)

### ISSUE THREAD

**Issue by sampengilly** [Kotlin/kotlinx-kover#363]
When your source files include values that aren't completely constant according to Kotlin (because of the function call) they get picked up as untested when there are reasons why they shouldn't be tested. For instance in Compose, values that represent layout dimensions:

```
private val IconToTextGap = 10.dp
```

This is picked up as an untested line

**Comment by shanshin** [comment]
Hi,

the basic approach used in Kover is that any custom code written by the user should be used.
If a constant is added, then it must either be read, deleted, or excluded from the report. 

Unfortunately, due to the peculiarities of the language, it is impossible to track the use of `const val`, but the use of the other `val` is tracked, even if the value is always the same.

**Comment by shanshin** [comment]
Close as not planned
