### ISSUE TITLE
Use existing report for koverVerify

### ISSUE THREAD

**Issue by BulatInDrive** [Kotlin/kotlinx-kover#496]
Is it possible to use an existing kover report (generated with `koverXmlReport`) when running `koverVerify`?
My case:
* I have a legacy and a new codebase. The legacy code is placed inside the app module. The new code is split into modules.
* I am generating coverage report using "include" only for the new modules.
* I need to run verify task on PRs, but only for modified files (I can pass a list of modified classes to the verify task). But now I have a problem that if the legacy code has also been modified, the verify task would fail. I can't "exclude" the legacy code, since its base path is contained in each modules path (since the legacy code is in the app).
So I have a "correct" xml report (only for the new code) and I want to use it for verification. Is this possible?

**Comment by shanshin** [comment]
Hi,
could you clarify, do you want to verify only those classes that have been changed?
If so, have you tried specifying "includes" filters for verification?

**Comment by shanshin** [comment]
Could you clarify which command you are running verification with?

If using the `koverVerify` command, then you need to configure the default verification report:
```
koverReport {
    defaults {
        
        verify {
            filters {
                includes {
                    classes(<list-of-classes>)
                }
            }
        }
        
    }
}
```

Specifying filters at the top level may not work due to the [bug](https://github.com/Kotlin/kotlinx-kover/issues/459).

**Comment by BulatInDrive** [comment]
I created a [sample project](https://github.com/BulatInDrive/KoverSample) to illustrate my case. 
But the main question remains the same: "Can a report created with `koverXmlReport` be used in a `koverVerify` task?".

**Comment by shanshin** [comment]
Answering the question:
> Can a report created with koverXmlReport be used in a koverVerify task?

No, Kover Gradle Plugin uses binary reports and cannot use previous data that was generated with other inputs.

According to your example: as far as I can see, if the command `:koverHtmlReport` is run, the `AppClassOne` class does not get into the report because the inclusion filter `tat.mukhutdinov.koversample.feature.*` is applied.
When the `classes(changedFiles.split(','))` filter for the verification rule is applied, the `tat.mukhutdinov.koversample.feature.*` filtering does not occur. Unfortunately, Kover summarizes the filters rather than checking them sequentially.

As a workaround, you can first filter the list of modified files, and then transfer them to the Kover filters - so you get a result similar to an HTML report.

In rule filters:
```
                filters {
                    includes {
                        classes(changedFiles.split(',').findAll {it.startsWith("tat.mukhutdinov.koversample.feature.") })
                    }
                }
```

**Comment by BulatInDrive** [comment]
Thank you!
