### ISSUE TITLE
Compose end line are not covered in coverage 

### ISSUE THREAD

**Issue by ds-griddynamics** [Kotlin/kotlinx-kover#601]
**Describe the bug**
When generating coverage compose last lines are not covered check screenshot, I have tried will all next version `0.7.x` and `0.8.x` none of them are working.

**Errors**
If present, stacktraces or files from `build/kover/errors` directory

**Expected behavior**

**Reproducer**

**Reports**
If applicable, report files or screenshots.

<img width="785" alt="Screenshot 2024-04-25 at 9 05 51 PM" src="https://github.com/Kotlin/kotlinx-kover/assets/151758119/d4476477-d937-409a-8730-583ebbbbf0ad">

**Environment**
 - Kover Gradle Plugin version: 0.6.1
 - Gradle version: 8.3.0
 - Kotlin project type: Kotlin/Android
 - Coverage Toolset : Kover
 - Other context important for this bug: [e.g. OS version]

**Comment by galex** [comment]
Got here because of the same issue! 

![Screenshot 2024-05-19 at 22 15 42](https://github.com/Kotlin/kotlinx-kover/assets/105982/9aba818f-143b-459e-852c-4c09a17ad837)

Start and end of this function are considered untested branches and instructions apparently. probably because of the magic of the Compose Compiler that adds `$composer` and other parameters and code... 🤔

**Comment by shanshin** [comment]
Fixed in `0.8.2`
