### ISSUE TITLE
How to generate multiple reports for different gradle tasks?

### ISSUE THREAD

**Issue by rafal-danowski-allegro** [Kotlin/kotlinx-kover#614]
Hi, I haven't found any clue how to do it properly, without any hacks, that's why I created this question.
I've got a project, where we have two tests sets - unit and integration. I'd like to have two different reports for each suite, to see how well our tests cover all instructions. Currently I'm able to generate only one report for one of these cases, leaving other blank.

I'd like to achieve behavior specified below:
- my pipeline runs `check` task, where unit and integration tasks are run (and other checks, like KtLint),
- for both tests suites I'd like to have separate `koverVerify` tasks, with different bound values and types (e.g. for unit tests I'd like to have 80% of instructions covered, for integration tests it would be 90% of lines),
- after checking I'd like to generate XML report for each sutes,
- both of these reports would be available to be posted as PR comment (preferably only one), that would show how well code is covered by each tests type separately.

Is it possible to achieve specified behavior with current state of project? If so, could you provide me with examples or docs that would guide me how to do it?

**Comment by shanshin** [comment]
Hi,
since version `0.8.0` you may use custom report variants.
A similar question: https://github.com/Kotlin/kotlinx-kover/issues/609

To write a more appropriate use case, we need to know the type of project.
You can try to find examples that suit you in the [documentation](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#build-types) yourself.
