### ISSUE TITLE
Module-specific report filters are ignored in merged project report

### ISSUE THREAD

**Issue by tonykolomeytsev** [Kotlin/kotlinx-kover#622]
Hello! I use kover in multimodule android project for generating reports for single modules and for the  whole project (aggregated project report). The project contains both Android and JVM submodules. 

When I run `:koverHtmlReport`, I get the aggregated HTML report with only filtering rules from root `build.gradle`. But specific rules from the subprojects' `build.gradle` are ignored. Is it expected behavior?

Kover 0.8.0

**Comment by shanshin** [comment]
Yes, this is the expected behavior.

The block `kover { reports { ... } }` configures only those Kover tasks that are located in the same module in which this config is specified.

So, if you specify filters in the root project, then these filters will affect only the result of the `:koverHtmlReport` task, if you specify filters in subproject `child`, then of the `:child:koverHtmlReport` task, etc.

If you are using the root project to aggregate coverage reports (create a merged report), then you need to configure the block `kover { reports { ... } }` **only** in the root project.

**Comment by shanshin** [comment]
Closed as answered.
Feel free to create new issue if you have any additional questions.
