### ISSUE TITLE
Only run instrumentation on demand?

### ISSUE THREAD

**Issue by stiost** [Kotlin/kotlinx-kover#64]
As applying Kover to our build is almost doubling the build time we need to be able to configure instrumentation to only run on demand (on a server). I expected this to only be a matter of running `gradle build koverReport` on the server, and `gradle build` locally, but it seems to increase build time drastically no matter what.

I tried adding
```
kover {
    enabled = false
}
```
 but then for people who want to run with coverage locally `gradle build koverReport` did nothing (as expected really).

Any suggestions?

**Comment by shanshin** [comment]
Hi, 
at the moment, Kover can't be disabled without changing the build script. However, you can configure the script to disable the plugin using the project property.

For example
```
kover {
    isEnabled = !hasProperty("disableKover")
}
```
you can use any name instead of `disableKover`

And then for a local build with the disabled Kover, do
```
gradle build -PdisableKover
```
(or pass the parameter value in any other convenient way)
