### ISSUE TITLE
How to create the "total report" in an Android MultiModule project

### ISSUE THREAD

**Issue by OneFiveFour** [Kotlin/kotlinx-kover#710]
**Describe what you would like to clarify about Kover**

I sucessfully added kover to my Android mutlimodule project as convention plugin (see below). The Kover documentation states multiple times that Kover is able to create a **"total report"** containing all results from all modules in one report. This is exactly what I want, but I cannot find how to get to this kind of report. Currently each module gets its own report. 
An example or more information about that in the documentation would be highly appreciated!

applied to each feature module (JVM/Kotlin-only as well as Android-modules):
```
class KoverPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            pluginManager.apply("org.jetbrains.kotlinx.kover")

            subprojects {
                pluginManager.apply("org.jetbrains.kotlinx.kover")
            }
        }
    }
}
```

libs.version.toml
```
kover = "0.8.3"

[libraries]
kover-gradlePlugin = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
```

app.build.gradle
```
plugins {
    alias(libs.plugins.kover)
}
```

**Comment by shanshin** [comment]
Hi,
please refer to the documentation chapter [Kotlin multi-module Android project](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#kotlin-multi-module-android-project), there is section [Merging reports from different modules](https://kotlin.github.io/kotlinx-kover/gradle-plugin/#merging-reports-from-different-modules-1).

To generate a merged report in one project, you need to add kover dependencies to all other modules, for example in build.gradle[.kts]
```kotlin
dependencies {
    kover(project(":feature-1"))
    kover(project(":feature-2"))
    // etc
}
```

And it is also important to call the report generation only for this project, to which this `dependencies` block was added.

for example, if it is added to the `:app` project, then you need to run the `:app:koverHtmlReport` task

**Comment by OneFiveFour** [comment]
Awesome, thank you very much. That was the last missing piece.

**Comment by igorwojda** [comment]
This is quite unfortunate design choice. 

Most projects will need a single "total report" - project usually have wide amount of feature modules (20.50/more), so bunch of dependencies are now required to create a total report...   this should be a singe line "generate total report true/false setting for entire project".

**Comment by shanshin** [comment]
> This is quite unfortunate design choice.

This is the result of following the Gradle [Project Isolation](https://docs.gradle.org/current/userguide/isolated_projects.html) and [Configuration Cache](https://docs.gradle.org/current/userguide/configuration_cache.html) recommendations.

If project isolation violations are allowed in your project, you can use [special shortcuts](https://kotlin.github.io/kotlinx-kover/gradle-plugin/dokka/-kover%20-gradle%20-plugin/kotlinx.kover.gradle.plugin.dsl/-kover-project-extension/merge.html).

> this should be a singe line "generate total report true/false setting for entire project"

In many cases, the project configuration is noticeably more complicated, because it is not always necessary to run all tests for all subprojects and Andoid build variants within the same build.

For a simple case where you need to measure coverage for everything you run in one build, please try using [Kover settings plugin](https://kotlin.github.io/kotlinx-kover/gradle-plugin/aggregated.html).
