### ISSUE TITLE
Omitting common package directories

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [Kotlin/kotlinx-kover#99]
Kotlin convention is omitting the common package directories, but third-party tools are not working well with this, but I am not sure if it is caused by Kover or the lack of support of them (Sonarqube and Codacy).

I checked there are two properties:
- `<package name="com/javiersc/kover/repro/library/jvm">`
- `<class name="com/javiersc/kover/repro/library/jvm/SomeClassJvm"`

Third-party tools are unable to know that the root package is being omitted so they are finding the files in the wrong directory.

Is there any property that can be provided and is currently missing by Kover (Jacoco and IntelliJ)?

Jacoco is having this issue for years, but should be great Kover can help to expand this convention. https://github.com/jacoco/jacoco/issues/939

**Comment by shanshin** [comment]
Hi,
Kotlin does not necessarily omit common packages, a class from any package can be located in an arbitrary directory. eg:
`src/main/kotlin/foo/bar/MyFile.kt` with class
```
package com.example

class MyClass 
```

Kover cannot change the XML file format because it is fixed and defined by JaCoCo itself.

After compilation, all class files are arranged according to their package, regardless of the directory in the source code. If we change the value of the `name` attribute in XNL-file, then third-party utilities will not be able to find the class without knowing the structure of the source code directories (name of the directory of the source file may not be present in the class-file).

That is, the only way to fix this issue is to fix the consumer of the coverage report by changing the way class files are searched in them  (whether it's a reporter, or Sonarqube etc)
